version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: modzero
      POSTGRES_PASSWORD: modzero
      POSTGRES_DB: modzero
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U modzero -d modzero"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://modzero:modzero@db:5432/modzero
      TRUST_WEIGHT_POSTURE: ${TRUST_WEIGHT_POSTURE:-0.7}
      TRUST_WEIGHT_CONTEXT: ${TRUST_WEIGHT_CONTEXT:-0.3}
      TRUST_MIN_THRESHOLD: ${TRUST_MIN_THRESHOLD:-70}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID:-}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET:-}
    ports:
      - "8000:8000"

volumes:
  db_data: