version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: modzero
      POSTGRES_PASSWORD: modzero
      POSTGRES_DB: modzero
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U modzero -d modzero"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:012202twz@db:5432/modzero
      SECRET_KEY: supersecretkey
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
      # placeholder for Azure credentials if needed
      AZURE_TENANT_ID: ${AZURE_TENANT_ID:-}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET:-}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/dist:/app/frontend/dist  # mount built frontend for serving static files

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data: