#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
#  ModZero Connector — Linux One-Click Installation Script
# ═══════════════════════════════════════════════════════════════════════
#
#  Usage:
#    curl "https://<controller>/public/connector/setup.sh" | sudo \
#      MODZERO_CONTROLLER_URL="https://<controller>" \
#      MODZERO_ENROLL_TOKEN="<token>" \
#      MODZERO_NETWORK="<network>" \
#      MODZERO_LABEL_DEPLOYED_BY="linux" \
#      bash
#
# ═══════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Branding ─────────────────────────────────────────────────────────
BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
CYAN="\033[36m"
RESET="\033[0m"

log()   { echo -e "${GREEN}[ModZero]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[ModZero WARN]${RESET} $*"; }
err()   { echo -e "${RED}[ModZero ERROR]${RESET} $*"; exit 1; }

# ── Required environment variables ───────────────────────────────────
: "${MODZERO_CONTROLLER_URL:?Missing MODZERO_CONTROLLER_URL}"
: "${MODZERO_ENROLL_TOKEN:?Missing MODZERO_ENROLL_TOKEN}"
MODZERO_NETWORK="${MODZERO_NETWORK:-default}"
MODZERO_LABEL_HOSTNAME="${MODZERO_LABEL_HOSTNAME:-$(hostname)}"
MODZERO_LABEL_DEPLOYED_BY="${MODZERO_LABEL_DEPLOYED_BY:-linux}"
MODZERO_CA_BUNDLE_PATH="${MODZERO_CA_BUNDLE_PATH:-}"
MODZERO_IMAGE="${MODZERO_IMAGE:-modzero/connector:latest}"
MODZERO_CONNECTOR_LISTEN_PORT="${MODZERO_CONNECTOR_LISTEN_PORT:-8443}"

CONFIG_DIR="/etc/modzero-connector"
CONTAINER_NAME="modzero-connector-$(head -c4 /dev/urandom | xxd -p)"
SERVICE_NAME="modzero-connector"

# ── Banner ───────────────────────────────────────────────────────────
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║    ModZero Connector — Automated Setup       ║"
echo "  ║    Zero-Trust Dynamic Security System        ║"
echo "  ╚══════════════════════════════════════════════╝"
echo -e "${RESET}"

# ── Pre-flight checks ───────────────────────────────────────────────
log "Checking prerequisites..."

# Must run as root (or with sudo) to install Docker and manage services
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (use sudo)"
fi

# ── Step 1: Ensure Docker is installed ───────────────────────────────
if command -v docker &>/dev/null; then
    log "Docker found: $(docker --version)"
else
    warn "Docker not found. Attempting to install Docker..."
    if command -v apt-get &>/dev/null; then
        apt-get update -qq
        apt-get install -y -qq docker.io
    elif command -v yum &>/dev/null; then
        yum install -y docker
        systemctl enable docker
        systemctl start docker
    elif command -v dnf &>/dev/null; then
        dnf install -y docker
        systemctl enable docker
        systemctl start docker
    else
        err "Cannot auto-install Docker. Install Docker manually: https://docs.docker.com/get-docker/"
    fi

    if ! command -v docker &>/dev/null; then
        err "Docker installation failed. Install manually: https://docs.docker.com/get-docker/"
    fi
    log "Docker installed successfully: $(docker --version)"
fi

# Ensure Docker daemon is running
if ! docker info &>/dev/null; then
    log "Starting Docker daemon..."
    systemctl start docker 2>/dev/null || service docker start 2>/dev/null || true
    sleep 2
    if ! docker info &>/dev/null; then
        err "Docker daemon is not running. Start it with: systemctl start docker"
    fi
fi

# ── Step 2: Create config directory ──────────────────────────────────
log "Creating config directory ${CONFIG_DIR}..."
mkdir -p "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

# Write configuration file
cat > "${CONFIG_DIR}/config.env" <<ENVEOF
# ModZero Connector Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
MODZERO_CONTROLLER_URL=${MODZERO_CONTROLLER_URL}
MODZERO_NETWORK=${MODZERO_NETWORK}
MODZERO_LABEL_HOSTNAME=${MODZERO_LABEL_HOSTNAME}
MODZERO_LABEL_DEPLOYED_BY=${MODZERO_LABEL_DEPLOYED_BY}
MODZERO_CONNECTOR_LISTEN_PORT=${MODZERO_CONNECTOR_LISTEN_PORT}
ENVEOF

# Store enroll token temporarily (will be consumed on first run)
echo "${MODZERO_ENROLL_TOKEN}" > "${CONFIG_DIR}/enroll_token"
chmod 600 "${CONFIG_DIR}/config.env" "${CONFIG_DIR}/enroll_token"

if [[ -n "${MODZERO_CA_BUNDLE_PATH}" ]]; then
    echo "MODZERO_CA_BUNDLE_PATH=/etc/modzero-connector/ca-bundle.crt" >> "${CONFIG_DIR}/config.env"
    if [[ -f "${MODZERO_CA_BUNDLE_PATH}" ]]; then
        cp "${MODZERO_CA_BUNDLE_PATH}" "${CONFIG_DIR}/ca-bundle.crt"
        chmod 600 "${CONFIG_DIR}/ca-bundle.crt"
        log "Custom CA bundle copied to ${CONFIG_DIR}/ca-bundle.crt"
    fi
fi

log "Configuration written to ${CONFIG_DIR}/config.env (mode 600)"

# ── Step 3: Pull container image ─────────────────────────────────────
log "Pulling connector image: ${MODZERO_IMAGE}..."
docker pull "${MODZERO_IMAGE}" 2>/dev/null || warn "Could not pull image — will use local build if available"

# ── Step 4: Stop existing connector (if any) ─────────────────────────
if docker ps -a --format '{{.Names}}' | grep -q "^${SERVICE_NAME}$"; then
    log "Stopping existing connector container..."
    docker stop "${SERVICE_NAME}" 2>/dev/null || true
    docker rm "${SERVICE_NAME}" 2>/dev/null || true
fi

# ── Step 5: Create and start the container ───────────────────────────
log "Starting connector container..."

ENROLL_TOKEN_VALUE=$(cat "${CONFIG_DIR}/enroll_token")

docker run -d \
    --env MODZERO_CONTROLLER_URL="${MODZERO_CONTROLLER_URL}" \
    --env MODZERO_ENROLL_TOKEN="${ENROLL_TOKEN_VALUE}" \
    --env MODZERO_NETWORK="${MODZERO_NETWORK}" \
    --env MODZERO_LABEL_HOSTNAME="${MODZERO_LABEL_HOSTNAME}" \
    --env MODZERO_LABEL_DEPLOYED_BY="${MODZERO_LABEL_DEPLOYED_BY}" \
    --env MODZERO_CONNECTOR_LISTEN_PORT="${MODZERO_CONNECTOR_LISTEN_PORT}" \
    ${MODZERO_CA_BUNDLE_PATH:+--env MODZERO_CA_BUNDLE_PATH=/etc/modzero-connector/ca-bundle.crt} \
    -v "${CONFIG_DIR}:/etc/modzero-connector" \
    -p "${MODZERO_CONNECTOR_LISTEN_PORT}:${MODZERO_CONNECTOR_LISTEN_PORT}" \
    --name "${SERVICE_NAME}" \
    --restart=unless-stopped \
    "${MODZERO_IMAGE}"

# Remove plaintext enroll token from disk (it's now in the container env for first run)
rm -f "${CONFIG_DIR}/enroll_token"

# ── Step 6: Create systemd service (optional, for management) ────────
if command -v systemctl &>/dev/null; then
    log "Creating systemd service for connector management..."
    cat > /etc/systemd/system/modzero-connector.service <<SVCEOF
[Unit]
Description=ModZero Connector (Docker)
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/docker start ${SERVICE_NAME}
ExecStop=/usr/bin/docker stop ${SERVICE_NAME}
ExecReload=/usr/bin/docker restart ${SERVICE_NAME}

[Install]
WantedBy=multi-user.target
SVCEOF
    systemctl daemon-reload
    systemctl enable modzero-connector.service 2>/dev/null || true
    log "Systemd service created: modzero-connector.service"
fi

# ── Step 7: Verify ───────────────────────────────────────────────────
sleep 3
log "Checking connector status..."

if docker ps --filter "name=${SERVICE_NAME}" --format '{{.Status}}' | grep -q "Up"; then
    echo ""
    echo -e "${GREEN}${BOLD}  Connector is RUNNING${RESET}"
    echo ""
    docker logs "${SERVICE_NAME}" --tail 10 2>/dev/null || true
    echo ""
    log "Connector health check endpoint: http://localhost:${MODZERO_CONNECTOR_LISTEN_PORT}/healthz"
else
    echo ""
    echo -e "${RED}${BOLD}  Connector failed to start!${RESET}"
    echo ""
    echo "  Recent logs:"
    docker logs "${SERVICE_NAME}" --tail 20 2>/dev/null || true
    echo ""
    echo -e "${YELLOW}Troubleshooting:${RESET}"
    echo "  1. Check logs:           docker logs ${SERVICE_NAME}"
    echo "  2. Verify controller:    curl ${MODZERO_CONTROLLER_URL}/health"
    echo "  3. Check network:        docker network ls"
    echo "  4. Restart:              docker restart ${SERVICE_NAME}"
    echo "  5. Config directory:     ls -la ${CONFIG_DIR}"
    exit 1
fi

echo ""
echo -e "${CYAN}${BOLD}Setup complete!${RESET}"
echo ""
echo "  Useful commands:"
echo "    docker logs -f ${SERVICE_NAME}       # Follow logs"
echo "    docker restart ${SERVICE_NAME}       # Restart connector"
echo "    docker stop ${SERVICE_NAME}          # Stop connector"
echo "    systemctl status modzero-connector   # Service status"
echo ""
exit 0
