server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/modzero.crt;
    ssl_certificate_key /etc/nginx/certs/modzero.key;

    location / {
        proxy_pass http://host.docker.internal:8088;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }
}
